apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.replicas.count }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.image.registry}}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.app.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.app.port }}
          initialDelaySeconds: 3
          periodSeconds: 3