apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - {{ .Values.domain.name }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.domain.name }}
      http:
        paths:
        - backend:
            serviceName: {{ .Values.app.name }}
            servicePort: 80
          path: /